sudo: false
dist: xenial
language: python
python: # test various python versions (Django Support for various python versions is described within the exclude: section)
  - "3.6"
  - "3.7"
  - "3.8"
  - "pypy3" # PyPy3
  - "3.8-dev"  # 3.8 development branch
  - "nightly"  # nightly build
env:
  - DJANGO=2.0
  - DJANGO=2.1
  - DJANGO=2.2
  - DJANGO=master
matrix:
  allow_failures:
    # newer python versions aswell as pypy may also always break our build
    - python: "pypy3"
    - env: DJANGO=master
cache:
  directories:
    - $HOME/.cache/pip
install: pip install tox-travis
script: tox
